services:
  zent-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: zent-app
    ports:
      - "3001:3000"
    restart: unless-stopped

  zent-app-2:
    image: zent-app
    ports:
      - "3002:3000"
    restart: unless-stopped

  zent-app-3:
    image: zent-app
    ports:
      - "3003:3000"
    restart: unless-stopped
