name: zent-pipeline

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:

  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set image name
        run: echo "IMAGE_NAME=zent-app-pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build Docker image for PR
        run: |
          docker build -f Dockerfile.build -t $IMAGE_NAME .

      - name: Cleanup PR image
        run: |
          docker rmi $IMAGE_NAME || true

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t zent-app .

      - name: Remove old containers
        run: |
          docker rm -f zent-app-1 zent-app-2 zent-app-3 || true

      - name: Run 3 instances
        run: |
          docker run -d -p 3001:3000 --name zent-app-1 --restart unless-stopped zent-app
          docker run -d -p 3002:3000 --name zent-app-2 --restart unless-stopped zent-app
          docker run -d -p 3003:3000 --name zent-app-3 --restart unless-stopped zent-app

      - name: Cleanup unused images
        run: |
          docker image prune -af || true
